services:
  database:
    container_name: postgres
    image: postgres:17.4-alpine3.21
    ports:
      - "20001:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "test `psql -U postgres kifucho -c '\\dt' -t | wc -l` = 3" ]
      interval: 1s
      timeout: 30s
      retries: 10
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: "Asia/Tokyo"
  gql-server:
    container_name: hasura
    image: hasura/graphql-engine:v2.47.0.cli-migrations-v3.ubuntu
    ports:
      - "20002:8080"
    volumes:
      - ./gql-server/metadata:/hasura-metadata
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/kifucho
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: hasura
volumes:
  db:
