services:
  database:
    container_name: kifucho-postgres
    image: postgres:17.5-alpine3.21
    ports:
      - "20001:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: kifucho
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: "Asia/Tokyo"
  graphql-engine:
    container_name: kifucho-hasura
    image: hasura/graphql-engine:v2.45.3.ubuntu
    ports:
      - "20002:8080"
    restart: always
    depends_on:
      - database
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@kifucho-postgres:5432/kifucho
      HASURA_GRAPHQL_ENABLE_CONSOLE: false
      HASURA_GRAPHQL_DEV_MODE: true
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: hasura
      HASURA_GRAPHQL_JWT_SECRET: |
        {
          "type": "RS512",
          "key": "-----BEGIN CERTIFICATE-----\nMIIDAzCCAeugAwIBAgIJdXMfnitdOrxaMA0GCSqGSIb3DQEBCwUAMB8xHTAbBgNV\nBAMTFGtpZnVjaG8uanAuYXV0aDAuY29tMB4XDTI1MDUwMzA3MzUwMFoXDTM5MDEx\nMDA3MzUwMFowHzEdMBsGA1UEAxMUa2lmdWNoby5qcC5hdXRoMC5jb20wggEiMA0G\nCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDKExpDUPDkDRYZ5FKdKzzCC5eKhTgs\n6I+++7pSfX8aMLoEvQZMj/s7ogx2xHHkInVA3xw3xpl8BcDpDnV7c1AmkYjcjNcQ\nRmYOg1uPSboeIoBlLeckSmb0IUyx/vjGNFd/h3bDxehbon2Yc/WTG4Jm3e8Y2mBC\nUM2aADxOsqSkO5o6ISOXf+y9YoxjZvPnaT2ETmWs1ENODpaxDLHGB/71f8xynmX/\n8dUTEcneWsOxZk3EURk/3abcQFWNy7hPdGid8PJ2dTzwzApj5TZoSnQg1MeCIPEl\ntj3fl9rjDdJoR32Pv2jUw25HA2D0UPMYbXWdwMHvr69wWGfzgZ2waktJAgMBAAGj\nQjBAMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFFxgFEd5lh0qN5NzBgkXbKQ4\nrNJ7MA4GA1UdDwEB/wQEAwIChDANBgkqhkiG9w0BAQsFAAOCAQEAjJf1e64driuy\nUDwtoyxVk3ZnorIqbjWf6hSJ3aoWzLK7Iau5CgcIftSbGENnx2Y7roVMRNO/pfq1\nZ/rPS0Mh4milcYvZJqPWXIg70ujxBcn9390lxPWJRu+SebKy6AbXiuCT91lSJILq\nma2WCkfrB8khyQqXituKWCqZrN4r00OAuJcEuwZBg6nGPLPiP0fjMRGgINWLxlpN\n1DHlYaxuLO6HJeXDPc0ki+tkO7P/dOQCtfNhw7/fk3BVXi/JTjf1hCMgJ1Ms7EO/\nQUj7OF/4GwlcLhWJUBIwVcuBQQ5KV7TaW2tO3sTGXEnDq9/r18d4fVNakM9CQZKj\nLJkPVrtJrA==\n-----END CERTIFICATE-----",
          "allowed_skew": 86400
        }
volumes:
  db:
