table:
  name: users
  schema: public
array_relationships:
  - name: records
    using:
      foreign_key_constraint_on:
        column: owned_by
        table:
          name: records
          schema: public
select_permissions:
  - role: user
    permission:
      columns:
        - id
        - name
      filter:
        id:
          _eq: X-Hasura-User-Id
    comment: ""
